-- ==========================================================
-- Database Migration & Seed: Verification Roster
-- Maktab Kauzariyya Directory (Teachers & Students)
-- ==========================================================

-- 1. Ensure columns exist on users and students tables
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `gender` ENUM('male', 'female') NOT NULL DEFAULT 'male' AFTER `full_name`;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `roster_id` INT UNSIGNED DEFAULT NULL AFTER `google_id`;
ALTER TABLE `students` ADD COLUMN IF NOT EXISTS `parent_phone` VARCHAR(30) DEFAULT NULL AFTER `parent_name`;

-- 2. Create verification_roster table
CREATE TABLE IF NOT EXISTS `verification_roster` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `type` ENUM('teacher', 'student') NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  `assigned_teacher_name` VARCHAR(200) DEFAULT NULL,
  `is_claimed` TINYINT(1) DEFAULT 0,
  `claimed_user_id` INT UNSIGNED DEFAULT NULL,
  `claimed_at` DATETIME DEFAULT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX (`type`),
  INDEX (`name`),
  INDEX (`is_claimed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Seed Teachers & Ustads
INSERT INTO `verification_roster` (`type`, `name`, `assigned_teacher_name`) VALUES
('teacher', 'HUDAIF USTAD', NULL),
('teacher', 'NOOH USTAD', NULL),
('teacher', 'SUHAIL USTAD', NULL),
('teacher', 'ASHIF USTAD', NULL),
('teacher', 'USMAN USTAD', NULL),
('teacher', 'JAUHAR USTAD', NULL),
('teacher', 'ABBAS USTAD', NULL),
('teacher', 'ALTHAF ISMAIL USTAD', NULL),
('teacher', 'NIZAR USTAD', NULL),
('teacher', 'ABDULLA KP USTAD', NULL),
('teacher', 'ALTHAF KO USTAD', NULL),
('teacher', 'FAWAZ USTAD', NULL),
('teacher', 'ABDULRAHMAN USTAD', NULL),
('teacher', 'ANAS USTAD', NULL),
('teacher', 'MUHSIN USTAD', NULL),
('teacher', 'BILAL USTAD', NULL),
('teacher', 'ALTHAF MANARI USTAD', NULL),
('teacher', 'BILAL TDP USTAD', NULL),
('teacher', 'ABID USTAD', NULL),
('teacher', 'HASEEB USTAD', NULL),
('teacher', 'ANSIF USTAD', NULL),
('teacher', 'ABDULLA IBRAHIM USTAD', NULL),
('teacher', 'AMEEN USTAD', NULL),
('teacher', 'YASEEN USTAD', NULL),
('teacher', 'IHSAN USTAD', NULL),
('teacher', 'ADIL USTAD', NULL),
('teacher', 'ASHIQ USTAD', NULL),
('teacher', 'ALTHAF USTAD KOLLAM', NULL),
('teacher', 'THAHA USTAD', NULL),
('teacher', 'SUMAYYA TEACHER', NULL),
('teacher', 'FATHIMA TK TEACHER', NULL),
('teacher', 'ADHILA TEACHER', NULL),
('teacher', 'AYISHA HUSAIN TEACHER', NULL),
('teacher', 'RUSHDA TEACHER', NULL),
('teacher', 'MANSOORA TEACHER', NULL),
('teacher', 'AMINA TEACHER', NULL),
('teacher', 'FIDA TEACHER', NULL),
('teacher', 'HALEEMA ZUBAIR TEACHER', NULL),
('teacher', 'HANAN TEACHER', NULL),
('teacher', 'AYISHA KABEER TEACHER', NULL),
('teacher', 'AYISHA S TEACHER', NULL),
('teacher', 'HIBA TEACHER', NULL),
('teacher', 'FATHIMA ZAHRA TEACHER', NULL),
('teacher', 'HIBA SHERIN TEACHER', NULL),
('teacher', 'AISHA S TEACHER', NULL);

-- 4. Seed Students & Teacher Mappings (73 Students)
INSERT INTO `verification_roster` (`type`, `name`, `assigned_teacher_name`) VALUES
('student', 'MIRZA', 'NOOH USTAD'),
('student', 'SHANAVAS KOCHI', 'SUHAIL USTAD'),
('student', 'NOUFAL', 'ASHIF USTAD'),
('student', 'FAHEEM', 'ASHIF USTAD'),
('student', 'AMMAR WASEEM Pathanamthitta', 'USMAN USTAD'),
('student', 'SAINUDHEEN', 'JAUHAR USTAD'),
('student', 'SALMAN JAMSHEER', 'ABBAS USTAD'),
('student', 'SANEEJ', 'ALTHAF ISMAIL USTAD'),
('student', 'IZAN SANEEJ', 'NIZAR USTAD'),
('student', 'IMRAN', 'ASHIF USTAD'),
('student', 'IMAAD', 'ABDULLA KP USTAD'),
('student', 'FADHIL JANEESH', 'ALTHAF KO USTAD'),
('student', 'DHAKIR', 'FAWAZ USTAD'),
('student', 'TUFAIL', 'ABDULRAHMAN USTAD'),
('student', 'KHALID', 'ANAS USTAD'),
('student', 'ZAID', 'MUHSIN USTAD'),
('student', 'AMAN', 'MUHSIN USTAD'),
('student', 'YASEEN', 'MUHSIN USTAD'),
('student', 'HAMDAN', 'BILAL USTAD'),
('student', 'HISHAM ADIVADU BALIGAN', 'ALTHAF MANARI USTAD'),
('student', 'ADHIL BALIGAN', 'ALTHAF MANARI USTAD'),
('student', 'RAFI KOLLAM', 'FAWAZ USTAD'),
('student', 'AMEEN KANJIRAPALLY', 'BILAL TDP USTAD'),
('student', 'AMEEN PUNE', 'ABID USTAD'),
('student', 'PCS MUZAMMIL', 'BILAL TDP USTAD'),
('student', 'JAMSHEER MLV', 'FAWAZ USTAD'),
('student', 'ALTHAF TDP', 'HASEEB USTAD'),
('student', 'ANSHAD SAUDI', 'SUHAIL USTAD'),
('student', 'ANAS', 'ANSIF USTAD'),
('student', 'FARHAN BALIGAN', 'ANAS USTAD'),
('student', 'SHAN MUMBAI CL 9', 'ABDULLA IBRAHIM USTAD'),
('student', 'MINHAJ', 'AMEEN USTAD'),
('student', 'NOUFAL KOLLAM', 'ABDULLA IBRAHIM USTAD'),
('student', 'ASHEHAD', 'ABDULLA KP USTAD'),
('student', 'AFFAN MALA', 'YASEEN USTAD'),
('student', 'ISADUL ALI', NULL),
('student', 'MUAD', 'IHSAN USTAD'),
('student', 'YAHYA', 'ANSIF USTAD'),
('student', 'AMIR YAHYA', 'ABDULLA KP USTAD'),
('student', 'AHMAD ADIL', 'ADIL USTAD'),
('student', 'ALTHAF SALAHUDHEEN', 'ASHIQ USTAD'),
('student', 'ABDULLA ILYAS MLV', 'ANSIF USTAD'),
('student', 'UMARUL FAROOQ', 'ALTHAF USTAD KOLLAM'),
('student', 'MUZAMMIL FAIZAL', 'THAHA USTAD'),
('student', 'UMAR FAIZAL', 'THAHA USTAD'),
('student', 'SUMAYYA IBRAHIM', 'SUMAYYA TEACHER'),
('student', 'NISA ADHIL UMMA', 'FATHIMA TK TEACHER'),
('student', 'SWALIHA FATHIMA', 'SUMAYYA TEACHER'),
('student', 'ABINA', 'ADHILA TEACHER'),
('student', 'ISHAN', 'AYISHA HUSAIN TEACHER'),
('student', 'HAMRA', 'RUSHDA TEACHER'),
('student', 'BEEMA', 'AYISHA HUSAIN TEACHER'),
('student', 'SHAHANA ITHA', 'MANSOORA TEACHER'),
('student', 'FILLATH', 'AMINA TEACHER'),
('student', 'AJMIYA', 'MANSOORA TEACHER'),
('student', 'AIZA SANEEJ', 'FIDA TEACHER'),
('student', 'HAZINE SANEEJ', 'FIDA TEACHER'),
('student', 'HAAZIQ SANEEJ', 'RUSHDA TEACHER'),
('student', 'IZZA EDATHALA', 'HALEEMA ZUBAIR TEACHER'),
('student', 'HANNA', 'HANAN TEACHER'),
('student', 'ZULAIKHA', 'AYISHA KABEER TEACHER'),
('student', 'SUMAYYA', 'AYISHA S TEACHER'),
('student', 'HIBA', 'AYISHA S TEACHER'),
('student', 'AMNA DUBAI', 'HIBA TEACHER'),
('student', 'IHAAN', 'FATHIMA ZAHRA TEACHER'),
('student', 'SHAHANA SHAMSHEER', 'AYISHA KABEER TEACHER'),
('student', 'NADIYA', 'ADHILA TEACHER'),
('student', 'YAQUB', 'HALEEMA ZUBAIR TEACHER'),
('student', 'ASIYA NASRIN', 'AYISHA HUSSAIN TEACHER'),
('student', 'IMRAN JEDDAH', 'HIBA SHERIN TEACHER'),
('student', 'NAJUMA', 'HIBA SHERIN TEACHER'),
('student', 'FATHIMA ZAHRA CHRNLR', 'AISHA S TEACHER'),
('student', 'SUHAILA', NULL);
